apiVersion: v1
kind: Namespace
metadata:
  name: optimized-ai-system
  labels:
    name: optimized-ai-system
    environment: production
    version: v1.0.0
  annotations:
    description: "Ultra-fast AI system with optimized response times"
    contact: "haole3435@gmail.com"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-system-quota
  namespace: optimized-ai-system
spec:
  hard:
    requests.cpu: "50"
    requests.memory: 200Gi
    requests.nvidia.com/gpu: "10"
    limits.cpu: "100"
    limits.memory: 400Gi
    limits.nvidia.com/gpu: "10"
    persistentvolumeclaims: "20"
    services: "20"
    secrets: "50"
    configmaps: "50"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: ai-system-limits
  namespace: optimized-ai-system
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim

